Homework 30 is done
MayHoax/robot_dreams_homework pull request #13
Opened 2023-04-06 09:01 UTC by MayHoax

2023-04-06 17:39 UTC, klymenok requested changes

2023-04-06 17:39 UTC, klymenok commented on R_D_HW_30/API_2.py
> +    weathercode_dict = weather_dict = {
Винесіть це за межі циклу, щоб не перезаписувати словник при кожній ітерації

2023-04-06 17:39 UTC, klymenok commented on R_D_HW_30/API_2.py
> +    response_dict = json.loads(response.text)
Для отримання даних у вигляді dict ви можете використати `response.json()`

2023-04-06 17:39 UTC, klymenok commented on R_D_HW_30/API_2.py
> +    city_latitude = round(response_dict.get('results')[0]['latitude'], 2)
Ваша програма припинить свою роботу в цьому місці, якщо користувач введе місто, якого не існує

2023-04-07 06:41 UTC, MayHoax commented on R_D_HW_30/API_2.py
> +    response_dict = json.loads(response.text)
Как метод либы request, без надобности импорта json ?

2023-04-09 21:09 UTC, klymenok commented on R_D_HW_30/API_2.py
> +    response_dict = json.loads(response.text)
Як метод обʼєкту Response, що повертає requests.get():
```
response = request.get('...')
response_dict = response.json()
```

2023-04-09 21:10 UTC, klymenok approved these changes
Looks good!

2023-04-10 11:09 UTC, merged