9th homework is done
MayHoax/robot_dreams_homework pull request #5
Opened 2023-01-17 02:47 UTC by MayHoax

2023-01-18 20:33 UTC, klymenok requested changes

2023-01-18 20:33 UTC, klymenok commented on R_D_HW_9/homework_9_generator.py
> +    print(next_fib)
Your program print a wrong number in the sequence. For example, for 7 it should print 13 but it prints 8.

2023-01-18 22:17 UTC, MayHoax commented
My bad, the sequence had an error with initial values. I used a sequence that had two 1s at the beginning.

2023-01-18 22:18 UTC, MayHoax commented
Now it's should return 13 if 7 given

2023-01-21 15:56 UTC, klymenok approved these changes
Looks good!

2023-01-21 19:38 UTC, merged